version: '3'
services:
  discount:
    build: .
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings:Server=postgres;Database=fu-capstone-discount;User Id=postgres;Password=1;
    depends_on:
      - postgres
    # command: dotnet ef database update
  postgres:
    image: postgres
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=fu-capstone-discount